# Generated by Django 5.0.4 on 2024-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="impact",
            field=models.TextField(null=True),
        ),
    ]
