# Generated by Django 5.0.4 on 2024-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_project_impact"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="impact",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="projectkeyaspects",
            field=models.TextField(null=True),
        ),
    ]
