# Generated by Django 5.0.4 on 2024-04-18 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_book_impact_project_projectkeyaspects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="benefits",
        ),
    ]
