# Generated by Django 5.0.4 on 2024-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_project_benefits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="impact",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectkeyaspects",
            field=models.TextField(),
        ),
    ]
