# Generated by Django 5.0.4 on 2024-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_project_impact_alter_project_projectkeyaspects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="impact",
            field=models.TextField(),
        ),
    ]
