# Generated by Django 5.0.4 on 2024-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_book_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="impact",
            field=models.TextField(),
        ),
    ]
